### PR TITLE
Switch from curl to reqwest for HTTP requests

### LINKED ISSUE #9: Openness to move from curl to reqwest?
Thanks for this project, and a huge thanks for tarpaulin!

I am in a corporate environment where CI builds are currently failing due to issues downloading the `curl` source code as part of the `curl-sys` crate (a dependency of the `curl` crate used by `coveralls-api`) while trying to `cargo install cargo-tarpaulin`. It looks like some firewall that is between our CI servers and the cargo registry is aborting the HTTP connection partially through the download of the curl source tarball.

While we are still troubleshooting the download issue, I was wondering if you would be open in principle to changing the crate used for performing HTTP requests from `curl` to `reqwest`? As far as I can tell, that crate, while slightly larger than curl, does not need to pull in non-rust libraries and compile them from source, and is the more widely used HTTP client library in Rust.

If you are open to this suggestion, I would be happy to take a stab at a PR.

### PR DESCRIPTION
**Pull request by sseemayer**
Closes #9

Instead of using the [curl](https://crates.io/crates/curl) crate that requires compiled-in curl libraries, this PR switches the used HTTP client to the [reqwest](https://crates.io/crates/reqwest) crate.

I was able to successfully pass all tests on my fork after setting up a coveralls token.

Note: It might make sense to refactor the crate API in a follow-up PR - having a separate `upload_status` function to check whether the upload was successful instead of returning the status of the HTTP request from the `send_to_*` methods seems more cumbersome than needed.

BREAKING CHANGES: 

1. the error type returned by the `send_to_coveralls` and `send_to_endpoint` functions has changed from `curl::Error` to `reqwest::Error`.
2. (`CoverallsReport` private fields have changed)

### CODE REVIEW

**Comment by sseemayer** [comment]
@xd009642 let me know what you think. I am also happy to make additional adjustments.

File: src/lib.rs [hunk 1]
```diff
@@ -425,36 +434,37 @@ impl CoverallsReport {
...
-            .unwrap();
-        self.handle.httppost(form).unwrap();
-        self.handle.perform()
+
+        let form = Form::new().part(
+            "json_file",
+            Part::bytes(body).mime_str("gzip/json")?.file_name("report"),
+        );
+
+        let response = self.client.post(url).multipart(form).send()?;
```
Comment (sseemayer) [inline src/lib.rs:455]: Note that this is now a blocking call, so looping on the value of `upload_status` does not make sense anymore. 

If you really want non-blocking, we could launch the client in a thread to keep the old polling behavior. Or, we could make a larger refactoring and move to `async` functions for sending requests, also using the `async` reqwest API.

Comment (xd009642) [reply src/lib.rs:455]: I am perfectly fine with a blocking API - after all tarpaulin would only use the blocking API :smile:

**Review by xd009642 — APPROVED** [review]
LGTM!
